[package]
name = "scan"
version = "0.2.0"
edition = "2021"

[dependencies]
rand          = { version = "0.8", features = ["small_rng", "std"] }
rand_chacha   = "0.3"
rayon         = "1.10"
csv           = "1.3"
indicatif     = "0.17"

# Your simulation crate
rc_sim        = { path = "../rc_sim" }   # adjust the path if needed

