[package]
name = "scan"
version = "0.2.0"
edition = "2021"

[dependencies]
rand         = { version = "0.8", features = ["small_rng", "std"] }
rand_chacha   = { version = "0.3" }
rayon         = { version = "1.10" }
csv           = { version = "1.3" }
indicatif     = { version = "0.17" }

# Your simulation crate
rc_sim        = { path = "../relational-contrast-sim" }   # Ensure the path points to the rc_sim crate. For example, if the project structure changes, verify the path using `ls ../rc_sim` or adjust it to the new location, such as `path = "./libs/rc_sim"`.

