[package]
name = "scan"
version = "0.2.0"
edition = "2021"

[dependencies]
rand         = { version = "0.8", features = ["small_rng", "std"] }
rand_chacha  = { version = "0.3" }
rayon        = { version = "1.10" }
csv          = { version = "1.3" }
indicatif    = { version = "0.17" }
nalgebra     = { version = "0.32" }
clap = { version = "4.5.39", features = ["derive"] }

[[bin]]
name = "wide_scan"
path = "src/bin/wide_scan.rs"

[[bin]]
name = "improved_narrow_scan"
path = "src/bin/improved_narrow_scan.rs"

[[bin]]
name = "fss_analysis"
path = "src/bin/fss_analysis.rs"

[[bin]]
name = "multi_size_scan"
path = "src/bin/multi_size_scan.rs"

[[bin]]
name = "generate_pairs"
path = "src/bin/generate_pairs.rs"

[[bin]]
name = "fss_narrow_scan"
path = "src/bin/fss_narrow_scan.rs"